/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as ScraperHealthRouteImport } from './routes/scraper-health'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as NichesRouteImport } from './routes/niches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminScrapersRouteImport } from './routes/admin.scrapers'

const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ScraperHealthRoute = ScraperHealthRouteImport.update({
  id: '/scraper-health',
  path: '/scraper-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const NichesRoute = NichesRouteImport.update({
  id: '/niches',
  path: '/niches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScrapersRoute = AdminScrapersRouteImport.update({
  id: '/admin/scrapers',
  path: '/admin/scrapers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/niches': typeof NichesRoute
  '/saved': typeof SavedRoute
  '/scraper-health': typeof ScraperHealthRoute
  '/targets': typeof TargetsRoute
  '/admin/scrapers': typeof AdminScrapersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/niches': typeof NichesRoute
  '/saved': typeof SavedRoute
  '/scraper-health': typeof ScraperHealthRoute
  '/targets': typeof TargetsRoute
  '/admin/scrapers': typeof AdminScrapersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/niches': typeof NichesRoute
  '/saved': typeof SavedRoute
  '/scraper-health': typeof ScraperHealthRoute
  '/targets': typeof TargetsRoute
  '/admin/scrapers': typeof AdminScrapersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/niches'
    | '/saved'
    | '/scraper-health'
    | '/targets'
    | '/admin/scrapers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/niches'
    | '/saved'
    | '/scraper-health'
    | '/targets'
    | '/admin/scrapers'
  id:
    | '__root__'
    | '/'
    | '/niches'
    | '/saved'
    | '/scraper-health'
    | '/targets'
    | '/admin/scrapers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NichesRoute: typeof NichesRoute
  SavedRoute: typeof SavedRoute
  ScraperHealthRoute: typeof ScraperHealthRoute
  TargetsRoute: typeof TargetsRoute
  AdminScrapersRoute: typeof AdminScrapersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraper-health': {
      id: '/scraper-health'
      path: '/scraper-health'
      fullPath: '/scraper-health'
      preLoaderRoute: typeof ScraperHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niches': {
      id: '/niches'
      path: '/niches'
      fullPath: '/niches'
      preLoaderRoute: typeof NichesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scrapers': {
      id: '/admin/scrapers'
      path: '/admin/scrapers'
      fullPath: '/admin/scrapers'
      preLoaderRoute: typeof AdminScrapersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NichesRoute: NichesRoute,
  SavedRoute: SavedRoute,
  ScraperHealthRoute: ScraperHealthRoute,
  TargetsRoute: TargetsRoute,
  AdminScrapersRoute: AdminScrapersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
